### ISSUE TITLE
OSError: Couldn't deserialize thrift: TProtocolException: Exceeded size limit

### ISSUE THREAD

**Issue by lintingyi2014** [hakyimlab/summary-gwas-imputation#25]
How may I solve this?

$ python gwas_summary_imputation.py -by_region_file $DATA/eur_ld.bed.gz -gwas_file harmonized.test.txt.gz -parquet_genotype $DATA/reference_panel_1000G/chr1.variants.parquet -parquet_genotype_metadata $DATA/reference_panel_1000G/variant_metadata.parquet -window 100000 -parsimony 7 -chromosome 1 -regularization 0.1 -frequency_filter 0.01 -sub_batches 10 -sub_batch 0 --standardise_dosages -output harmonized.test_chr1_sb0_reg0.1_ff0.01_by_region.txt.gz
INFO - Beginning process
INFO - Creating context by variant
INFO - Loading study
INFO - Loading variants' parquet file
Traceback (most recent call last):
  File "/e/summary-gwas-imputation/src/gwas_summary_imputation.py", line 97, in <module>
    run(args)
  File "/summary-gwas-imputation/src/gwas_summary_imputation.py", line 60, in run
    results = run_by_region(args)
  Fi/summary-gwas-imputation/src/gwas_summary_imputation.py", line 40, in run_by_region
    context = SummaryImputationUtilities.context_by_region_from_args(args)
  File "/vWAS_compile/summary-gwas-imputation/src/genomic_tools_lib/summary_imputation/Utilities.py", line 229, in context_by_region_from_args
    study = load_study(args)
  File "/vf/uWAS_compile/summary-gwas-imputation/src/genomic_tools_lib/summary_imputation/Utilities.py", line 162, in load_study
    study = Parquet.study_from_parquet(args.parquet_genotype, args.parquet_genotype_metadata, chromosome=args.chromosome)
  File "/vf/users/HumanRNAProject/TYL/DNA/GWAS_compile/summary-gwas-imputation/src/genomic_tools_lib/file_formats/Parquet.py", line 218, in study_from_parquet
    _v = pq.ParquetFile(variants)
  File "/data/lint6/conda/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 318, in __init__
    self.reader.open(
  File "pyarrow/_parquet.pyx", line 1470, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status

**Comment by yahyunee** [comment]
Hi, I'm facing same problem. Have you gone through it?

**Comment by wxz-456** [comment]
I'm facing same problem too, have you gone through it?

**Comment by lintingyi2014** [comment]
Yess sorry for the late response, you must use  pyarrow 0.9.0
